# Generated by Django 5.2.9 on 2026-01-26 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='Job',
        ),
        migrations.AlterField(
            model_name='apply',
            name='apply_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
