# Generated by Django 5.2.9 on 2026-03-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_savedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
