# Generated by Django 5.2.9 on 2026-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
